name: Use API Key in JavaScript

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Retrieve API Key
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: node use-api-key.js
